# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sysstatus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsysstatus.proto\x12\x03sys\"E\n\x08GeoPoint\x12\x10\n\x08latitude\x18\x01 \x01(\x05\x12\x11\n\tlongitude\x18\x02 \x01(\x05\x12\x14\n\x0c\x61ltitude_msl\x18\x03 \x01(\x02\"V\n\rOtherUAVState\x12\x0e\n\x06uav_id\x18\x01 \x01(\r\x12\x1f\n\x08position\x18\x02 \x01(\x0b\x32\r.sys.GeoPoint\x12\x14\n\x0cvelocity_ned\x18\x03 \x03(\x02\"\xfe\x01\n\x07UAVData\x12\x14\n\x0ctimestamp_us\x18\x01 \x01(\x04\x12\x0e\n\x06uav_id\x18\x02 \x01(\r\x12%\n\x0esafe_space_min\x18\x03 \x01(\x0b\x32\r.sys.GeoPoint\x12%\n\x0esafe_space_max\x18\x04 \x01(\x0b\x32\r.sys.GeoPoint\x12(\n\x11guidance_waypoint\x18\x05 \x01(\x0b\x32\r.sys.GeoPoint\x12\x14\n\x0c\x65xpire_at_us\x18\x06 \x01(\x04\x12\x15\n\rtraffic_count\x18\x07 \x01(\r\x12(\n\x0ctraffic_data\x18\x08 \x03(\x0b\x32\x12.sys.OtherUAVStateb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sysstatus_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GEOPOINT._serialized_start=24
  _GEOPOINT._serialized_end=93
  _OTHERUAVSTATE._serialized_start=95
  _OTHERUAVSTATE._serialized_end=181
  _UAVDATA._serialized_start=184
  _UAVDATA._serialized_end=438
# @@protoc_insertion_point(module_scope)
